backend:
  name: github
  repo: obouthaich3777/ibork-website
  branch: main
  base_url: https://decap-bridge.vercel.app
  auth_endpoint: /api/auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "catalog"
    label: "Catalogue"
    files:
      - file: "content/products.json"
        label: "Tous les Produits"
        name: "products_list"
        fields:
          - label: "Produits"
            name: "items"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Prix (DH)", name: "price", widget: "number" }
              - { label: "Marque", name: "brand", widget: "string" }
              - { label: "Catégorie", name: "category", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - label: "Images"
                name: "images"
                widget: "list"
                field: { label: "Image", name: "image", widget: "image" }